title: >
  Project Bridge: Bridging the Gap in Data Fragmentation for AEC 
  with AI-Powered Knowledge Retrieval
description: >
  An AI-powered knowledge management system for the AEC industry, 
  leveraging Retrieval-Augmented Generation (RAG) and agentic workflows. 
  Originally developed as a 2025 capstone project for the Google Gen-AI course on Kaggle, 
  the system addresses data fragmentation in multimodal AEC data by delivering interactive, 
  source-aware insights.

theme: jekyll-theme-cayman

sass:
  sass_dir: assets/css

